[project]
name = "file-mover"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "smbprotocol>=1.12.0",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "prek>=0.3.1",
    "ruff>=0.15.0",
]
